---
  - name: setup zookeeper stack
    cloudformation:
      stack_name: "zookeeper"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: cloudformation/zookeeper-stack.yml
      stack_policy: cloudformation/stack-policy.json
      template_parameters:
        AMI: "{{ami}}"
        HostedZoneName: "{{private_host_zone}}"
        InstanceType: "{{instance_type}}"
        KeyName: "{{keyname}}"
        VpcId: "{{vpc}}"
        Pkg: "{{pkg}}"
        PrivateSubnet1: "{{private_subnet_1}}"
        PrivateSubnet2: "{{private_subnet_2}}"
        PrivateSubnet3: "{{private_subnet_3}}"
        Zk01AZ: "{{zk01az}}"
        Zk02AZ: "{{zk02az}}"
        Zk03AZ: "{{zk03az}}"
        Zk01RecordName: "{{zk1name}}"
        Zk02RecordName: "{{zk2name}}"
        Zk03RecordName: "{{zk3name}}"
        S3Repository: "{{s3repository}}"
        S3Region: "{{s3region}}"
      tags:
        project: "{{project}}"
        application: zookeeper
        lob: MyFun
        env: "{{env}}"