---
  - name: setup frontend stack
    cloudformation:
      stack_name: "{{application}}-{{ab}}-{{version}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/frontend.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BusinessUnit: "{{business_unit}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        ECRRegistry: "{{deployment_ecr}}"
        HpECRRepo: "{{hp_ecr_repo}}"
        HostedZoneName: "{{public_zone}}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{key_name}}"
        MaxSize: "{{max_asg_size}}"
        MinSizeAS: "{{min_asg_size}}"
        NewRelicRPM: "{{new_relic_rpm}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
        NginxECRRepo: "{{nginx_ecr_repo}}"
        PagerDutyArn: "{{low_pager_duty_arn}}"
        HPagerDutyArn: "{{high_pager_duty_arn}}"
        SrpPdpECRRepo: "{{srp_pdp_ecr_repo}}"
        RecordName: "{{application}}-{{ab}}-{{version}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        SSLCertificateARN: "{{ssl_cert_arn}}"
        SubnetID: "{{private_subnets}}"
        SumoLogicInstallerFileName: "{{sumo_logic_installer}}"
        SumoLogicAccessId: "{{sumo_logic_access_id}}"
        SumoLogicAccessKey: "{{sumo_logic_access_key}}"
        VPC: "{{aws_vpc_id}}"
        VpcCidr: "{{vpc_cidr}}"
        VpcDns: "{{vpc_dns}}"
        WebserviceCount: "{{web_service_count}}"
        HpserviceCount: "{{hp_service_count}}"
        SrpserviceCount: "{{srp_service_count}}"

      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"
