AWSTemplateFormatVersion: '2010-09-09'
Description: setup an static ELB
Parameters:
  LoadBalancerName:
    Description: Name of the load balancer
    Type: String
  AppPort:
    Description: Application Http port for HealthCheck
    Type: String
  InstancePort:
    Description: Instance port from ELB forwarded to
    Type: String
  Subnets:
    Description: The subnets which the ELB is hosted.
    Type: CommaDelimitedList
  VpcID:
    Description: Id of the VPC
    Type: String
    AllowedPattern: vpc-[a-f0-9]{8}
  Application:
    Description: application name
    Type: String
  Scheme:
    Description: scheme of ELB
    Type: String
    Default: internet-facing
  CertificateARN:
    Description: arn of SSL certificate
    Type: String
  IdleTimeout:
    Description: The number of seconds a connection can be idle before load balancer
      closes the connection
    Type: String
    Default: '180'
Resources:
  ELBConnectionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [' ', [Allowing, !Ref 'Application', client connection]]
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
      VpcId: !Ref 'VpcID'
  ELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Scheme: !Ref 'Scheme'
      Subnets: !Ref 'Subnets'
      SecurityGroups:
      - !Ref 'ELBConnectionSecurityGroup'
      LoadBalancerName: !Ref 'LoadBalancerName'
      CrossZone: true
      ConnectionSettings:
        IdleTimeout: !Ref 'IdleTimeout'
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 60
      Listeners:
      - InstancePort: !Ref 'InstancePort'
        LoadBalancerPort: '443'
        Protocol: 'HTTPS'
        SSLCertificateId: !Ref 'CertificateARN'
      - InstancePort: !Ref 'InstancePort'
        LoadBalancerPort: '80'
        Protocol: 'HTTP'
      HealthCheck:
        Target: TCP:80
        HealthyThreshold: '3'
        UnhealthyThreshold: '3'
        Interval: '30'
        Timeout: '5'
Outputs:
  ELBEndpoint:
    Description: ELB dns name.
    Value: !GetAtt [ELB, DNSName]
