AWSTemplateFormatVersion: '2010-09-09'
Description: 'MySQL RDS for Squarefoot'
Parameters:
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
  Subnets:
    Type: CommaDelimitedList
    Description: The list of SubnetIds, for at least two Availability Zones in the
      region in your Virtual Private Cloud (VPC)
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUsername:
    Default: admin
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    Default: admin
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '1'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBClass:
    Default: db.m4.large
    Description: Database instance class
    Type: String
    ConstraintDescription: must select a valid database instance type.
  DBAllocatedStorage:
    Default: '100'
    Description: The size of the database (Gb)
    Type: Number
    MinValue: '5'
    MaxValue: '1024'
    ConstraintDescription: must be between 5 and 1024Gb.
  BackupRetentionPeriod:
    Default: '20'
    Description: Backup retention period of RDS in days
    Type: Number
    MinValue: '5'
    MaxValue: '100'
  PubliclyAccessible:
    Description: Can the database be accesed publicly
    Type: String
  EngineVersion:
    Description: Mysql Engine Version
    Type: String
  BusinessUnit:
    Description: Business Unit
    Type: String
  BillingTag:
    Description: Billing Tag
    Type: String
Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Ref 'Subnets'
  VPCSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS DB Instance.
      VpcId: !Ref 'VpcId'
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: !Ref 'DBAllocatedStorage'
      DBInstanceClass: !Ref 'DBClass'
      Engine: MySQL
      EngineVersion: !Ref 'EngineVersion'
      MasterUsername: !Ref 'DBUsername'
      MasterUserPassword: !Ref 'DBPassword'
      DBSubnetGroupName: !Ref 'MyDBSubnetGroup'
      BackupRetentionPeriod: !Ref 'BackupRetentionPeriod'
      MultiAZ: 'true'
      Port: 3306
      VPCSecurityGroups:
      - !Ref 'VPCSecurityGroup'
      Tags:
      - Value: !Ref 'BusinessUnit'
        Key: "business unit"
      - Value: !Ref 'BillingTag'
        Key: Billing
Outputs:
  JDBCConnectionString:
    Description: JDBC connection string for database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt [MyDB, Endpoint.Address], ':', !GetAtt [
          MyDB, Endpoint.Port], /, !Ref 'DBName']]
