---
  - name: setup squarefoot frontend stack
    cloudformation:
      stack_name: "frontend-{{ab}}-{{build}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/frontend-stack.yml"
      stack_policy: "cloudformation/stack-policy.json"
      template_parameters:
        SubnetID: "{{public_subnets}}"
        BillingTag: "{{project}}"
        MinSizeAS: "{{min_asg_size}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        MaxSize: "{{max_asg_size}}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{key_name}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        SumoLogicInstallerFileName: "{{sumo_logic_installer_file_name}}"
        SumoLogicAccessId: "{{sumo_logic_access_id}}"
        SumoLogicAccessKey: "{{sumo_logic_access_key}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"
