---
  - name: setup frontend stack
    cloudformation:
      stack_name: "frontend-{{ab}}-{{build}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/frontend.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BillingTag: "{{project}}"
        BusinessUnit: "{{business_unit}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        ECRRegistry: "{{deployment_ecr}}"
        HpECRRepo: "{{hp_ecr_repo}}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{key_name}}"
        MaxSize: "{{max_asg_size}}"
        MinSizeAS: "{{min_asg_size}}"
        NewRelicRPM: "{{new_relic_rpm}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
        NginxECRRepo: "{{nginx_ecr_repo}}"
        SrpPdpECRRepo: "{{srp_pdp_ecr_repo}}"
        RecordName: "{{dns_hostname}}.{{public_zone}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        SSLCertificateARN: "{{ssl_certificate_arn}}"
        SubnetID: "{{public_subnets}}"
        SumoLogicInstallerFileName: "{{sumo_logic_installer}}"
        SumoLogicAccessId: "{{sumo_logic_access_id}}"
        SumoLogicAccessKey: "{{sumo_logic_access_key}}"
        VPC: "{{aws_vpc_id}}"
        VpcCidr: "{{vpc_cidr}}"
        VpcDns: "{{vpc_dns}}"

      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"
