---
  - name: setup squarefoot frontend stack
    cloudformation:
      stack_name: "frontend-{{ab}}-{{build}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/frontend.yml"
      stack_policy: "cloudformation/stack-policy.json"
      template_parameters:
        BillingTag: "{{project}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{key_name}}"
        MaxSize: "{{max_asg_size}}"
        MinSizeAS: "{{min_asg_size}}"
        NewRelicRPM: "{{new_relic_rpm}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
        RecordName: "frontend-{{ab}}-{{build}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        SubnetID: "{{public_subnets}}"
        SumoLogicInstallerFileName: "{{sumo_logic_installer}}"
        SumoLogicAccessId: "{{sumo_logic_access_id}}"
        SumoLogicAccessKey: "{{sumo_logic_access_key}}"

      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"
