---
  - name: setup an static ELB
    cloudformation:
      stack_name: "{{elb_stack_name}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/elb.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        VpcID: "{{aws_vpc_id}}"
        AppPort: "{{app_port}}"
        Subnets: "{{subnets}}"
        LoadBalancerName: "{{load_balancer_name}}"
        Application: "{{application}}"
        InstancePort: "{{instance_port}}"
        Scheme: "{{scheme}}"
        CertificateARN: "{{ssl_cert_arn}}"
        IdleTimeout: "{{elb_idle_timeout}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"

