---
  - name: setup squarefoot stack
    cloudformation:
      stack_name: "squarefoot-{{ab}}-{{build}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/squarefoot-stack.yml"
      stack_policy: "cloudformation/stack-policy.json"
      template_parameters:
        SubnetID: "{{public_subnets}}"
        BillingTag: "{{env}}"
        MinSizeAS: "{{min_asg_size}}"
        DesiredCapacity: "{{desired_asg_capacity}}"
        MaxSize: "{{max_asg_size}}"
        Instancestype: "{{ecs_instance_type}}"
        KeyNamessh: "{{ecs_key_name_ssh}}"
      tags:
        project: "{{project}}"
        application: "{{project}}"
        lob: regional-web
        env: "{{env}}"