---
  - name: setup zookeeper stack
    cloudformation:
      stack_name: "zookeeper-{{ab}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/squarefoot/zookeeper.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        AMI: "{{ami}}"
        HostedZoneName: "{{private_zone}}"
        InstanceType: "{{instance_type}}"
        KeyName: "{{key_name}}"
        VpcId: "{{aws_vpc_id}}"
        Pkg: "{{pkg}}"
        PrivateSubnet1: "{{private_subnet_1}}"
        PrivateSubnet2: "{{private_subnet_2}}"
        PrivateSubnet3: "{{private_subnet_3}}"
        Zk01RecordName: "{{zk1name}}"
        Zk02RecordName: "{{zk2name}}"
        Zk03RecordName: "{{zk3name}}"
        S3Repository: "{{resource_bucket_name}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"