---
- name: create capi adapter
  cloudformation:
    stack_name: "{{adapter_name}}-{{build_number}}"
    state: present
    region: "{{aws_region}}"
    disable_rollback: true
    template: "cloudformation/squarefoot/capi-adapter.yml"
    stack_policy: "policies/cloudformation/stack-policy.json"
    template_parameters:
      BillingTag: "{{project}}"
      BusinessUnit: "{{business_unit}}"
      DesiredCapacity: "{{desired_asg_capacity}}"
      AdapterName: "{{adapter_name}}"
      ECR: "{{deployment_ecr}}"
      InstanceType: "{{instance_type}}"
      KeyPair: "{{key_name}}"
      MaxSizeASG: "{{max_size_asg}}"
      MinSizeASG: "{{min_size_asg}}"
      RecordName: "{{adapter_name}}-{{build_number}}"
      PrivateSubnets: "{{private_subnets}}"
      PublicSubnets: "{{public_subnets}}"
      HostPort: "{{host_port}}"
      ContainerPort: "{{container_port}}"
      VpcId: "{{aws_vpc_id}}"
      BuildNumber: "{{build_number}}"
      AZs: "{{zones}}"
      SumoLogicAccessId: "{{sumo_logic_access_id}}"
      SumoLogicAccessKey: "{{sumo_logic_access_key}}"

    tags:
      project: "{{project}}"
      application: "capi-suggestion-adapter-{{project}}"
      lob: "international"
      env: "{{env}}"
