---
  - name: setup rds db stack
    cloudformation:
      stack_name: "{{project}}-{{application}}-{{ab}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/squarefoot/rds.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        VpcId: "{{aws_vpc_id}}"
        Subnets: "{{rds_subnets}}"
        DBName: "{{db_name}}"
        DBUsername: "{{db_username}}"
        DBPassword: "{{db_password}}"
        DBClass: "{{db_class}}"
        DBAllocatedStorage: "{{db_allocated_storage}}"
        BackupRetentionPeriod: "{{backup_duration}}"
        HostedZoneName: "{{rds_zone}}"
        PubliclyAccessible: "{{public_access}}"
        DBInstanceIdentifier: "{{project}}-{{application}}-{{ab}}"
        Engine: "{{db_engine}}"
        EngineVersion: "{{db_engine_version}}"
        ParameterGroupVersion: "{{db_parameter_group_version}}"
        Port: "{{db_port}}"
        PagerDutyArn: "{{low_pager_duty_arn}}"
        BillingTag: "{{project}}"
        BusinessUnit: "{{business_unit}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"