---
  - name: setup solr stack
    cloudformation:
      stack_name: "solr-{{ab}}"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/squarefoot/solr.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        AMI: "{{ami}}"
        HostedZoneName: "{{private_zone}}"
        InstanceType: "{{instance_type}}"
        KeyName: "{{key_name}}"
        VpcID: "{{aws_vpc_id}}"
        Pkg: "{{pkg}}"
        RecordName: solr
        AppPort: '8983'
        AB: "{{ab}}"
        AvailabilityZones: "{{solr_az}}"
        PrivateSubnets: "{{solr_subnet}}"
        ASGMaxSize: "{{as_max}}"
        ASGMinSize: "{{as_min}}"
        ResourceBucketName: "{{resource_bucket_name}}"
        JVMHeapSize: "{{jvm_heap_size}}"
        VpcNet: "{{vpc_cidr}}"
        ZkHosts: "{{solr_zk_hosts}}"
        NewRelicLicenseKey: "{{new_relic_license_key}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        lob: "regional-web"
        env: "{{env}}"